# Generated by Django 5.1.4 on 2026-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('start_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', '待接单'), ('ACCEPTED', '已接单'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', '未支付'), ('PAID', '已支付'), ('REFUNDED', '已退款')], default='UNPAID', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
