# Generated by Django 5.1.4 on 2026-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('type', models.CharField(choices=[('FAST', '快充'), ('SLOW', '慢充')], max_length=10)),
                ('power', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('IDLE', '空闲'), ('CHARGING', '充电中'), ('FAULTY', '故障'), ('MAINTENANCE', '维护')], default='IDLE', max_length=20)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('installed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
