# Generated by Django 5.1.4 on 2026-06-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('BUS', '公交'), ('TAXI', '出租'), ('RIDE_HAILING', '网约车'), ('LOGISTICS', '物流')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('OPERATING', '运营中'), ('MAINTENANCE', '维修中'), ('DISABLED', '停用/报废'), ('PENDING', '待审核')], default='PENDING', max_length=20)),
                ('insurance_expiry', models.DateField()),
                ('lat', models.DecimalField(decimal_places=7, default=31.2304, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=121.4737, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
